//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubstrateNET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using SubstrateNET.RestClient.Mockup.Generated.Interfaces;
   using SubstrateNET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAssetsControllerMockupClient AssetsControllerClient;
      public IAuthorityDiscoveryControllerMockupClient AuthorityDiscoveryControllerClient;
      public IAuthorshipControllerMockupClient AuthorshipControllerClient;
      public IBabeControllerMockupClient BabeControllerClient;
      public IBagsListControllerMockupClient BagsListControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public IBountiesControllerMockupClient BountiesControllerClient;
      public IChildBountiesControllerMockupClient ChildBountiesControllerClient;
      public IContractsControllerMockupClient ContractsControllerClient;
      public IConvictionVotingControllerMockupClient ConvictionVotingControllerClient;
      public ICouncilControllerMockupClient CouncilControllerClient;
      public IDemocracyControllerMockupClient DemocracyControllerClient;
      public IElectionProviderMultiPhaseControllerMockupClient ElectionProviderMultiPhaseControllerClient;
      public IElectionsControllerMockupClient ElectionsControllerClient;
      public IGiltControllerMockupClient GiltControllerClient;
      public IGrandpaControllerMockupClient GrandpaControllerClient;
      public IIdentityControllerMockupClient IdentityControllerClient;
      public IImOnlineControllerMockupClient ImOnlineControllerClient;
      public IIndicesControllerMockupClient IndicesControllerClient;
      public ILotteryControllerMockupClient LotteryControllerClient;
      public IMmrControllerMockupClient MmrControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public INominationPoolsControllerMockupClient NominationPoolsControllerClient;
      public IOffencesControllerMockupClient OffencesControllerClient;
      public IPreimageControllerMockupClient PreimageControllerClient;
      public IProxyControllerMockupClient ProxyControllerClient;
      public IRandomnessCollectiveFlipControllerMockupClient RandomnessCollectiveFlipControllerClient;
      public IRecoveryControllerMockupClient RecoveryControllerClient;
      public IReferendaControllerMockupClient ReferendaControllerClient;
      public ISchedulerControllerMockupClient SchedulerControllerClient;
      public ISessionControllerMockupClient SessionControllerClient;
      public ISocietyControllerMockupClient SocietyControllerClient;
      public IStakingControllerMockupClient StakingControllerClient;
      public IStateTrieMigrationControllerMockupClient StateTrieMigrationControllerClient;
      public ISudoControllerMockupClient SudoControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITechnicalCommitteeControllerMockupClient TechnicalCommitteeControllerClient;
      public ITechnicalMembershipControllerMockupClient TechnicalMembershipControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITipsControllerMockupClient TipsControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public ITransactionStorageControllerMockupClient TransactionStorageControllerClient;
      public ITreasuryControllerMockupClient TreasuryControllerClient;
      public IUniquesControllerMockupClient UniquesControllerClient;
      public IVestingControllerMockupClient VestingControllerClient;
      public IWhitelistControllerMockupClient WhitelistControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AssetsControllerClient = new AssetsControllerMockupClient(_httpClient);
         AuthorityDiscoveryControllerClient = new AuthorityDiscoveryControllerMockupClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerMockupClient(_httpClient);
         BabeControllerClient = new BabeControllerMockupClient(_httpClient);
         BagsListControllerClient = new BagsListControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         BountiesControllerClient = new BountiesControllerMockupClient(_httpClient);
         ChildBountiesControllerClient = new ChildBountiesControllerMockupClient(_httpClient);
         ContractsControllerClient = new ContractsControllerMockupClient(_httpClient);
         ConvictionVotingControllerClient = new ConvictionVotingControllerMockupClient(_httpClient);
         CouncilControllerClient = new CouncilControllerMockupClient(_httpClient);
         DemocracyControllerClient = new DemocracyControllerMockupClient(_httpClient);
         ElectionProviderMultiPhaseControllerClient = new ElectionProviderMultiPhaseControllerMockupClient(_httpClient);
         ElectionsControllerClient = new ElectionsControllerMockupClient(_httpClient);
         GiltControllerClient = new GiltControllerMockupClient(_httpClient);
         GrandpaControllerClient = new GrandpaControllerMockupClient(_httpClient);
         IdentityControllerClient = new IdentityControllerMockupClient(_httpClient);
         ImOnlineControllerClient = new ImOnlineControllerMockupClient(_httpClient);
         IndicesControllerClient = new IndicesControllerMockupClient(_httpClient);
         LotteryControllerClient = new LotteryControllerMockupClient(_httpClient);
         MmrControllerClient = new MmrControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         NominationPoolsControllerClient = new NominationPoolsControllerMockupClient(_httpClient);
         OffencesControllerClient = new OffencesControllerMockupClient(_httpClient);
         PreimageControllerClient = new PreimageControllerMockupClient(_httpClient);
         ProxyControllerClient = new ProxyControllerMockupClient(_httpClient);
         RandomnessCollectiveFlipControllerClient = new RandomnessCollectiveFlipControllerMockupClient(_httpClient);
         RecoveryControllerClient = new RecoveryControllerMockupClient(_httpClient);
         ReferendaControllerClient = new ReferendaControllerMockupClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerMockupClient(_httpClient);
         SessionControllerClient = new SessionControllerMockupClient(_httpClient);
         SocietyControllerClient = new SocietyControllerMockupClient(_httpClient);
         StakingControllerClient = new StakingControllerMockupClient(_httpClient);
         StateTrieMigrationControllerClient = new StateTrieMigrationControllerMockupClient(_httpClient);
         SudoControllerClient = new SudoControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TechnicalCommitteeControllerClient = new TechnicalCommitteeControllerMockupClient(_httpClient);
         TechnicalMembershipControllerClient = new TechnicalMembershipControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TipsControllerClient = new TipsControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         TransactionStorageControllerClient = new TransactionStorageControllerMockupClient(_httpClient);
         TreasuryControllerClient = new TreasuryControllerMockupClient(_httpClient);
         UniquesControllerClient = new UniquesControllerMockupClient(_httpClient);
         VestingControllerClient = new VestingControllerMockupClient(_httpClient);
         WhitelistControllerClient = new WhitelistControllerMockupClient(_httpClient);
      }
   }
}
